version: '2'
services:
  minio:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./data:/data
    ports:
      - 9030:9000
      - 9033:9001
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
      MINIO_ADDRESS: ':9000'
      MINIO_CONSOLE_ADDRESS: ':9001'